### ISSUE TITLE
Use msys2 for the AppVeyor build

### ISSUE THREAD

**Issue by rnestler** [gtk-rs/gtk#234]
I'm opening this to ask if it would be appreciated if I would change appveyor.yml to use msys2 to do the builds.
Advantages:
 - The [official guide](http://www.gtk.org/download/windows.php) to build on Windows recommends using msys2
 - Probably simpler build script

Disadvantages:
 - Only one GTK version supported

**Comment by gkoz** [comment]
I assume you're talking about getting libgtk+ from msys2 and not mingw -- I've not managed to achieve successful build with that mingw (https://github.com/gtk-rs/gtk/pull/218#discussion_r49073417).

Since our building instructions now suggest getting gtk from msys2, it's reasonable to actually test that. I wouldn't want to drop the current 3.14 variant just yet.

**Comment by rnestler** [comment]
Yes I'm talking about getting libgtk+ from the msys2 package. I put together a appveyor.yml that builds successfully: https://ci.appveyor.com/project/rnestler/gtk/build/1.0.3/job/6hk358eoero63gbq
