### ISSUE TITLE
No chance to set width chars

### ISSUE THREAD

**Issue by k0pernicus** [gtk-rs/gtk#285]
Hello guys!

I'm a noob for graphics application, and I try to move an entry's width characters.
I just create an ```entry```, set the placeholder and set a new width characters.

```
let entry = Entry::new();
entry.set_placeholder_text(Some("My search..."));
entry.set_width_chars(22);
```

The problem is that the entry is still as defaut...

This is the code I wrote:

```
if gtk::init().is_err() {
        println!("Failed to initialize GTK.");
        return;
    }

// ENTRY
let entry = Entry::new();
entry.set_placeholder_text(Some("My search..."));
entry.set_width_chars(22);

// WINDOW
let window = Window::new(WindowType::Toplevel);
window.connect_delete_event(|_, _| {
    // Stop the main loop.
    gtk::main_quit();
    // Let the default handler destroy the window.
    Inhibit(false)
});

window.set_title("Test");
window.set_position(WindowPosition::Center);
window.set_default_size(1280, 200);
window.add(&entry);
window.show_all();

// RUN
gtk::main();
```

Do you see what is the problem?

Also, I canno't use the method ```set_max_width_chars```...

**Comment by gkoz** [comment]
> The problem is that the entry is still as defaut...

I wasn't able to guess the expected behavior. To rehash the docs,

`set_width_chars` 

> Changes the size request of the entry to be about the right size for `n_chars` characters.

See the discussion of geometry management in the [`Widget`](http://gtk-rs.org/docs/gtk/struct.Widget.html) documentation. You can notice the method's effect if you remove the `window.set_default_size` call.

---

`entry.set_max_width_chars()` requires enabling feature `v3_12`. This is just a convenience method, you can go through `EntryBuffer` instead: `entry.get_buffer().set_max_length(Some(22))`.

**Comment by k0pernicus** [comment]
Oh crap - my bad, I thought this function update the size of each character in the entry, and not the width of the entry...
Sorry for that -_-
