### ISSUE TITLE
GdkRGBA to boxed value

### ISSUE THREAD

**Issue by Eroc33** [gtk-rs/gtk#337]
For some attributes on `ListStore` (e.g. `foreground-rgba`, `cell-background-rgba` etc.) to be set by a column value `GdkRGBA` needs to be convertible into a value.
Looking through some of the gtk+ code it seems this would be done with `g_value_set_boxed`, so it is possible at the moment, but it would be useful to, for example, implement `ToValue` for `GdkRGBA` so we don't need to use `gobject_sys` for this.

ETA: This seems to do what I'm after, I'm just not sure how to create a pull that adds this given the crate is mostly automatically generated

```
    let color = GdkRGBA{red:1.0,green:0.0,blue:0.0,alpha:1.0};
    let val = unsafe{
        let mut out_val = Value::uninitialized();
        {
            let stash = out_val.to_glib_none_mut();
            gobject_sys::g_value_init(stash.0 as *mut _,gdk_sys::gdk_rgba_get_type());
            gobject_sys::g_value_set_boxed(stash.0 as *mut _,&color as *const _ as *const libc::c_void);
        }
        out_val
    };
```

**Comment by gkoz** [comment]
First you'd need to make a `struct RGBA` in `gdk` similar to [this one](https://github.com/gtk-rs/cairo/blob/master/src/rectangle.rs) and then implement for it `StaticType` (by calling `gdk_rgba_get_type()`) and `SetValueOptional` (via `g_value_set_boxed`, that seems correct).
But I'm not sure how you'd use it because we don't have nice ways to access properties yet.

**Comment by sdroege** [comment]
This was fixed in gdk long ago
