### ISSUE TITLE
Include webkit2?

### ISSUE THREAD

**Issue by antoyo** [gtk-rs/gtk#383]
Hello.
I open this issue so that we can discuss about the inclusion of the `webkit2` binding in this organization.
Soon, I will publish one of my project which depends on `webkit2` so I will need to use a published crate for `webkit2`.

Will it cause some issues for you if I publish my own `webkit2` crate on crates.io?
Will I be able to transfer this crate to you in the future?
Or is it better for you to publish the crate by yourself?

What is your process for creating a new GTK-based binding crate?

Thanks.

**Comment by GuillaumeGomez** [comment]
For now, we use gir to generate most of our crates. If a crate doesn't have a gir.toml, it'll need much more work to be able to bind it and then to keep it up to date.

**Comment by antoyo** [comment]
I generated the binding using the gir tool.
You can see my current work [here](https://github.com/antoyo/webkit2-rs) (the sys crate is [there](https://github.com/antoyo/webkit2-sys-rs)).
The gir configuration is [here](https://github.com/antoyo/webkit2-rs/blob/master/gir/Gir_WebKit.toml) and the gir files are [there](https://github.com/antoyo/webkit2-sys-rs/tree/master/gir-files) and the config is [here](https://github.com/antoyo/webkit2-sys-rs/blob/master/conf/gir-webkit2.toml).

**Comment by GuillaumeGomez** [comment]
Then, I guess there is no issue. For moving your work in the organization, I need others' opinion as well.

What do you think @gkoz and @EPashkin?

**Comment by gkoz** [comment]
I guess it depends on how much of a hurry you're in ;) Thanks to semver it's not a big deal if you want to publish a crate today and figure this out later. However I'd recommend naming it `webkit2gtk` because it's not just webkit and it's the actual name of the library.

Integrating with the organization would involve
 * adding the necessary `.gir` files to the [`gir-files`](https://github.com/gtk-rs/gir-files) repo (but we don't hand-edit them so we'll have to make `gir` deal with the `quark` quirk),
 * adding a `webkit2gtk-sys` crate to the [`sys`](https://github.com/gtk-rs/sys) repo (we should also give it a cursory review, it could uncover some `gir` bugs),
 * generating some docs for it into [`lgpl-docs`](https://github.com/gtk-rs/lgpl-docs) (this isn't documented properly but it boils down to running gir in `doc` mode),
 * moving the main crate to `gtk-rs/webkit2gtk` and making it consistent with the other crates, e.g. adding a [build script](https://github.com/gtk-rs/gtk/blob/master/build.rs), a prelude, gir-related submodules, etc.

We can do it during the following week if no additional difficult bugs come to light.

**Comment by EPashkin** [comment]
Not sure that adding `webkit2gtk-sys` to `gtk-rs/sys` is good idea, as it will depends of extra library
(may be I'm just lazy, but not found version for windows/msys64).
May be better add it as is or include in `webkit2gtk`?

**Comment by GuillaumeGomez** [comment]
I agree with @EPashkin for the sys part. Let's avoid making optional dependencies mandatory.

**Comment by gkoz** [comment]
I'm not sure what kind of dependencies you're talking about. The repo is not a crate. `gtk-sys` won't get new dependencies. There might be slight complications with CI.

**Comment by GuillaumeGomez** [comment]
I'm talking about the weight. Adding webkit2gtk-sys will increase the repo size for something optional.

**Comment by gkoz** [comment]
I believe the repo size difference will not have any measurable impact on anything. Especially since people should be getting their crates from crates.io not git.

Having the generated sys crates in multiple crates sounds like strictly more work than in a single one.

**Comment by GuillaumeGomez** [comment]
I don't like the idea to have non-"core" code directly in the sys crates and the fact that with a slow connection, there'll be a difference.

**Comment by gkoz** [comment]
Fetching the `sys` repo will always be a rounding error compared to `gtk`. We've just spent any time that could possibly be saved by not including extra 0.5 MB of uncompressed text there.

**Comment by zmoazeni** [comment]
Just checking in to see if there are any updates on this. I'd like to use webkit2gtk from rust too.

**Comment by EPashkin** [comment]
@zmoazeni, take look at https://github.com/antoyo/webkit2gtk-rs

**Comment by antoyo** [comment]
This is done, so I'm closing this issue.
