### ISSUE TITLE
Chatting with Rust and GNOME devs?

### ISSUE THREAD

**Issue by jonathandturner** [gtk-rs/gtk#401]
Hey all - members from the Rust team and the GNOME team recently had their first meeting to talk about ways they could possibly work together to make the experience of writing GNOME apps/libs in Rust a bit better.

There are some notes here if you're interested: https://internals.rust-lang.org/t/rust-and-gnome-meeting-notes/4339

Would be great to get some input from the gtk-rs efforts as well, since I'm sure there is some experience here that also helps make that experience better.

Cheers!

**Comment by GuillaumeGomez** [comment]
Ah nice! Since there is a great number of items that have been talked about, it might be difficult to give just one "global" opinion on each of them. Maybe you have a solution to propose about this?

cc @gkoz @EPashkin

**Comment by jonathandturner** [comment]
Yeah agreed.  If you skim it and see specific topics, maybe it's good to focus on those?

Something too, was that there were particular pain points that people weren't sure how to solve.  For example, being able to subclass GObject somehow from Rust.  For those bigger question items, it seems like a good thing to attack from all sides.

**Comment by GuillaumeGomez** [comment]
We used a "trait hierarchy" (or "trait inheritance", whatever) for all types. So you can specify/filter a type by using it:

```rust
fn do_something<T: IsA<Window>>(w: &T)
```

And so any objects being a `Window` or one of its children will be able to be passed to this function. Using this system, you can even use Rust's strength by checking at compile-time instead of something doing at runtime. :D

PS: @gkoz, don't hesitate to correct me if I write something incorrect.

**Comment by gkoz** [comment]
@jonathandturner thanks for doing this. I'm not yet sure if there's anything to add to the summary you've got. We haven't implemented any kind of subclassing because our hands have largely been full with just the bindings side. However implementing (and generating) signal bindings is a bit of a precedent for this because it also involves calling Rust code from C and translating the types.

**Comment by aruiz** [comment]
Hey guys!

When we talk about subclassing we mean subclassing a GObject in GObject, not just from a Rust point of view, so that we can also then emit GObject introspection data and pass it as an argument to functions... etc.

**Comment by sdroege** [comment]
To clarify what @aruiz meant: subclassing a GObject type with all the GObject machinery but in Rust instead of C. E.g. creating a new GtkWidget subclass or whatever in Rust and being able to have GObject use it like any GObject defined in C (and be able to provide a C API/ABI around it).

**Comment by GuillaumeGomez** [comment]
@sdroege: Seems possible for me with a trait hierarchy as I said above.

**Comment by sdroege** [comment]
Yeah, you "just" need some code that creates the GObject/GObjectClass structs, fills in the virtual methods (+ FFI conversion from Rust to C and back), calls g_type_register_static(), etc. And does the same things for GInterfaces.

Doing it via macros or anything probably won't work (e.g. because no type information), you can always do it manually of course, or maybe via a compiler plugin. Or a macro where all the traits for the class hierarchy and the interfaces are passed in somehow, that might also work.

**Comment by sdroege** [comment]
Let's close this for now, there's nothing actionable here and a lot has happened in the last 4 years in this area :)
