### ISSUE TITLE
TextView set_top_margin and set_bottom_margin

### ISSUE THREAD

**Issue by mandeep** [gtk-rs/gtk#403]
It appears that set_top_margin and set_bottom_margin are missing from gtk/src/auto/text_view.rs. Is this something that needs to be implemented? If so I'd be happy to submit a pull request.

**Comment by GuillaumeGomez** [comment]
It is present from 3.18. Check if you enabled it.

**Comment by mandeep** [comment]
@GuillaumeGomez Does either the 0.1.0 crate or the git repository contain 3.18 features? Cargo is showing me otherwise in both cases.

**Comment by GuillaumeGomez** [comment]
They're both from 3.18 version and it seems we don't generate it yet. I think the problem is that we don't have gir files for this version yet so we can't do much. It's possible to add them by hand by it would be overkill.

Here is the list of changes in 3.18: https://developer.gnome.org/gtk3/stable/api-index-3-18.html#api-index-3.18

**Comment by mandeep** [comment]
I don't mind implementing them, however if you would rather wait and auto-generate the 3.18 changes, that's fine with me too.

**Comment by GuillaumeGomez** [comment]
Well, it's quite easy to do but I wonder if it's worth it.

Do you know when gir files for 3.18 (and above) will be available @EPashkin?

**Comment by EPashkin** [comment]
@GuillaumeGomez, for gtk, theoretically, you can get it from any `libgtk-3-dev` (http://packages.ubuntu.com/yakkety/amd64/libgtk-3-dev/filelist),

**Comment by EPashkin** [comment]
@gkoz tried get it from Fedora (https://github.com/gtk-rs/gir-files/tree/fedora-23), I not remember now, why he stopped
