### ISSUE TITLE
Radio buttons problem

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gtk#488]
Any functions of `RadioButton` that accepting `group: &[RadioButton]` not works in right way.
IMHO this due recreating GSList when passing it to ffi.
Bad cases:
```rust
let radio_size_10 = gtk::RadioButton::new_with_label(&[], "10x10");
let radio_group = radio_size_10.get_group();
let radio_size_20 = gtk::RadioButton::new_with_label(&radio_group, "20x20");

let radio_size_10 = gtk::RadioButton::new_with_label(&[], "10x10");
let radio_size_20 = gtk::RadioButton::new_with_label(&[], "20x20");
let group = vec![radio_size_10.clone(), radio_size_20.clone()];
radio_size_10.set_group(&group);
radio_size_20.set_group(&group);
```
Current good case:
```rust
let radio_size_10 = gtk::RadioButton::new_with_label(&[], "10x10");
let radio_size_20 = gtk::RadioButton::new_with_label_from_widget(&radio_size_10, "20x20");
let radio_size_30 = gtk::RadioButton::new_with_label(&[], "30x30");
radio_size_30.join_group(Some(&radio_size_10));
```

I propose ignore all these functions and create manual functions:
```rust
pub fn new() -> RadioButton;
pub fn new_with_label(label: &str) -> RadioButton;
pub fn new_with_mnemonic(label: &str) -> RadioButton;
```
and change first parameter in *_from_widget to nonoptional

**Comment by EPashkin** [comment]
Thanks @kbsymanz for noting that.

**Comment by EPashkin** [comment]
Other variant:
Ignore bad functions and create manual functions for all `*_from_widget` without `_from_widget` in name
```rust
    pub fn new(radio_group_member: Option<&RadioButton>) -> RadioButton {
        assert_initialized_main_thread!();
        unsafe {
            Widget::from_glib_none(ffi::gtk_radio_button_new_from_widget(radio_group_member.to_glib_none().0)).downcast_unchecked()
        }
    }
```

**Comment by EPashkin** [comment]
Renaming variant will results bad docs.

**Comment by EPashkin** [comment]
Third option that has minimal affect on docs: just ignore bad functions

**Comment by EPashkin** [comment]
@GuillaumeGomez Can you look at this issue again?
@sdroege Can you look about this too?

**Comment by GuillaumeGomez** [comment]
Well, for now the only solution is indeed to ignore these functions and write them ourselves. Except if you have something in mind?

**Comment by EPashkin** [comment]
I still stays on my proposal, as I understand you also agreed it.
I also thought about adding class for GSList<Widged> to remove recreating on call, but IMHO it don't worth.

**Comment by GuillaumeGomez** [comment]
It might be interesting though. Or at least to create a special function for it?

**Comment by sdroege** [comment]
@epashkin I'll take a look on Monday when I'm back at my computer. Maybe I'll have an idea, but your proposal of just disabling and manual implementation seems fine with me for now too. There are hopefully not too many cases like this

**Comment by sdroege** [comment]
The problem here is similar to why I proposed https://github.com/gtk-rs/glib/issues/174 . There are various cases where you want to *borrow* something that is returned from a C function, to be able to a) modify it, or b) to just peek at the "thing" without creating any potentially expensive copies, or c) like in this case pass it directly to another function and having it pointer identical to anything existing.

I think it would be beneficial to generally provide a trait that allows borrowing in both directions (from C and to C), and this should also be implemented for GSList. Instead of then always copying the GSList to a Vec or some slice, you would pass around the actual GSList pointer in some kind of wrapper struct which implements an appropriate Rust API (e.g. impl Iterator, len(), ...). It's still simple enough to convert that into a Vec then (Iterator::collect), but only requires doing that when actually needed.
For container types this also needs to distinguish between an owned container (transfer container) or a owned container + contained items (transfer full) or an unowned container (transfer none), and except for the transfer full case it would be a real borrow (i.e. involving an actual lifetime).

**Comment by EPashkin** [comment]
Problem with radiobuttons GSList (and other returned lists) that list returning from `get_group` need be readonly and very short lived (as it don't reflect changes it list with `g_slist_prepend` ). Don't know how to control it.
Passing rusted GSList also has problem because `gtk_radio_button_set_group` (and `new_*`) uses pretend and passed list no longer actual.
So currently I think that we better don't expose it to end-user.

**Comment by sdroege** [comment]
Currently that's the best solution, yes.

> Problem with radiobuttons GSList (and other returned lists) that list returning from get_group need be readonly and very short lived (as it don't reflect changes it list with g_slist_prepend ). Don't know how to control it.

The GtkRadioButton API is incredibly ugly, yes. 

>  Passing rusted GSList also has problem because gtk_radio_button_set_group (and new_*) uses pretend and passed list no longer actual.

That's not much of a problem really. It is still a valid list, it just does not include the newly prepended item. The only real problem is the g_slist_remove() inside set_group(): if you pass in a GSList that is a) the current list, and b) has this very radio button at the head, your GSList will be freed and becomes invalid.

As said, the GtkRadioButton API is incredibly ugly :) I don't think you can safely bind it, not in Rust or any other language, unless you write custom code for handling this specific case and consider all the peculiarities of the actual implementation. IMHO it should be marked as `skip` in gobject-introspection, you can't autogenerate bindings for it.


That's all independent/unrelated to the other things I mentioned in my comment though, which are more a general thing to consider.

**Comment by EPashkin** [comment]
Passing GSList also problem because if we pass same list to two buttons will result 2 lists in these buttons with different heads and same tail.
I agree that we need expand borrowing in other cases.

**Comment by sdroege** [comment]
> Passing GSList also problem because if we pass same list to two buttons will result 2 lists in these buttons with different heads and same tail.

Indeed. Might be worth filing a bug against GTK to get a useful replacement API, and/or just mark this one as `skip` in gobject-introspection.

**Comment by GuillaumeGomez** [comment]
Sure, see you in GTK+ 3.36. :D

**Comment by EPashkin** [comment]
Fourth option: https://github.com/gtk-rs/gtk/pull/529#issuecomment-308665526 by @sdroege.
This method also good.
