### ISSUE TITLE
EditableExt does not have signals

### ISSUE THREAD

**Issue by andy128k** [gtk-rs/gtk#582]
Subj

**Comment by EPashkin** [comment]
It moved http://gtk-rs.org/docs/gtk/trait.EditableSignals.html due complexity

**Comment by GuillaumeGomez** [comment]
All signals are ignored from the generation as you can see [here](https://github.com/gtk-rs/gtk/blob/master/Gir.toml#L685-L690).

Can this be changed now @EPashkin or is anything still missing? Btw, we should definitely comment methods in the generated file instead of not putting them if we ignore them, don't you think?

**Comment by EPashkin** [comment]
`connect_insert_text` currently can't generated.

**Comment by andy128k** [comment]
@EPashkin Thanks!
