### ISSUE TITLE
Add new trait : GtkStatusIcon

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gtk#6]
[original](https://github.com/jeremyletang/rgtk/issues/179).

**Comment by lidavidm** [comment]
Any progress on this? I'd be interested in working on this if not. I see there's already a bit of stuff in the codebase, though there's no trait for it yet.

**Comment by gkoz** [comment]
Since `GtkStatusIcon` is not a widget it looks like you can already take advantage of the generator work: take [this file](https://github.com/gkoz/gtk-rs-gtk/blob/object_reform_gir/src/auto/status_icon.rs), convert it to use the `glib_wrapper!` macro (change the `pub type` and `impl StaticType` bits similarly to [this diff](https://github.com/gtk-rs/gdk/commit/46f5e2279e9b2c094c1b749822f9b53786f2f7ca#diff-3bc8da73acd6444b537b0b419e5c728b)) and fix the commented out bits. I hope it's not too much at once ;) (I'm, not sure why the issue talks about a trait, because `GtkStatusIcon` doesn't seem to require adding any traits.)

This will take care of the class itself and then we can figure out the signals.

**Comment by lidavidm** [comment]
Ah, thanks! I have it working at a basic level now.

I also just realized that this is all deprecated...Apparently the replacement is `GNotification`, which doesn't look like a replacement at all. (Or using "platform-specific APIs".) There's also AppIndicator. All this is rather frustrating, but I guess it's irrelevant here.

**Comment by gkoz** [comment]
I agree that there doesn't seem to be a satisfactory replacement so that deprecation is annoying.

**Comment by gkoz** [comment]
I believe this has been obsoleted by #186 and then #221

**Comment by jonhoo** [comment]
Sorry to revive this old discussion, but a viable alternative alternative to `GtkStatusIcon` available anywhere? As @lidavidm points out, `GNotification` doesn't actually provide this feature. `AppIndicator` seems promising, but afaict, it's not a part of GTK, nor is there a Rust port for it? @gkoz, have you found anything that can fill this space following the deprecation?

**Comment by gkoz** [comment]
@jonhoo sadly a replacement still doesn't seem to exist. A [recent summary from Remmina](https://github.com/FreeRDP/Remmina/wiki/Systray-menu) supports this. Perhaps a Rust library could break new ground here if there was significant demand.

**Comment by jonhoo** [comment]
That's very interesting, but also disheartening. Thanks for the link!

**Comment by efyang** [comment]
Perhaps one could modify [this go library](https://github.com/cratonica/trayhost) to be able to use callbacks and translate most of it to rust (as we already have bindings to [`winapi`](https://crates.io/crates/winapi) and [`cocoa`](https://crates.io/crates/cocoa)), but we would still need good bindings to `libappindicator` to have linux support. It would be a pretty large amount of work to undertake.
