### ISSUE TITLE
Incorrect conversion of &[TargetEntry] in TargetList::new.

### ISSUE THREAD

**Issue by tmiasko** [gtk-rs/gtk#621]
Currently each entry is converted to glib independently, and then address of
one of them is passed to gtk_target_list_new. See https://github.com/gtk-rs/gtk/blob/d3fb35605254f794c4cf669f49d0cdfe09dfc9dc/src/target_list.rs#L10 for details. It will crash when passed more than one TargetEntry.

On the other hand, implementation in https://github.com/gtk-rs/gtk/blob/1efdfd8d9a9bafcd0c4f5c87816bbecc3930a1eb/src/widget.rs#L53
appears to be doing the correct thing.

**Comment by EPashkin** [comment]
Thanks for noticing this:
It because in target_list `t` has type `Vec::<* const ffi::GtkTargetEntry>` instead `Vec::<ffi::GtkTargetEntry>`.
There slightly strange `to_glib_none` implementation https://github.com/gtk-rs/gtk/blob/master/src/target_entry.rs#L65-L80, maybe it right.

PS. By way we can use `unsafe { t.push(*stash.0); }` in good implementation now.
