### ISSUE TITLE
Set data in a gtk::ListStore

### ISSUE THREAD

**Issue by sanpii** [gtk-rs/gtk#635]
It’s just a tracking issue for my project, please tell me when a method to set data in a `gtk::ListStore` is available.

**Comment by fengalin** [comment]
You should be able to use: [`insert_with_values`](http://gtk-rs.org/docs/gtk/prelude/trait.ListStoreExtManual.html#tymethod.insert_with_values).

**Comment by sanpii** [comment]
@fengalin oh great, thank you. Why it’s not listed as implemeted by `gtk::ListStore`?

**Comment by fengalin** [comment]
Because it's part of a trait. This trait is not only implemented by `gtk::ListStore`, but also by [`gtk::TreeModel`](http://gtk-rs.org/docs/gtk/prelude/trait.ListStoreExtManual.html#implementors). Take a look at [`WidgetExt`](http://gtk-rs.org/docs/gtk/trait.WidgetExt.html) for another trait with [multiple implementors](http://gtk-rs.org/docs/gtk/trait.WidgetExt.html#implementors-1).

Then, there is the `Manual` part in the trait's name which means that the binding for these functions couldn't be generated automatically from the introspection mechanisms. You don't have to worry about that though since this is part of the [`prelude`](http://gtk-rs.org/docs/gtk/prelude/index.html).
