### ISSUE TITLE
Implement BuilderExt::add_callback_symbols() and BuilderExt::connect_signals()

### ISSUE THREAD

**Issue by defcronyke** [gtk-rs/gtk#707]
These functions are needed to support using the callback function specified in the Handler field of a signal in Glade.

They are described here: https://developer.gnome.org/gtk3/stable/GtkBuilder.html#gtk-builder-add-callback-symbols
and here: https://developer.gnome.org/gtk3/stable/GtkBuilder.html#gtk-builder-connect-signals

And they are listed in gtk_sys here: https://github.com/gtk-rs/sys/blob/master/gtk-sys/src/lib.rs#L14874
and here: https://github.com/gtk-rs/sys/blob/master/gtk-sys/src/lib.rs#L14881

Is there something blocking the support of these two functions?

**Comment by sdroege** [comment]
This would require to implement something that can find the correct Rust function by name at runtime, and to check that the function has the required signature (otherwise it would be unsafe). It's not trivial

**Comment by PeterOGB** [comment]
Could the approach taken in pyGtk be used ?  There you either specify a class that contains all the handlers or provide and explicit mapping (via a dictionary) between the name specified in the glade file and a  python function.  Either would be better than having to manually connected every signal to a handler as it seems to be at the moment.   
PS:  I'm a Rust noob (but expereince gtk+ programmer).

**Comment by sdroege** [comment]
The problem is not how to provide the functions but how to do it in a safe way. We could simply require all signal handlers to be `Fn(&[glib::Value]) -> Option<glib::Value>` and that would be safe then, but not very nice to use.

The problem is that in Rust we can't at runtime check what the signature of a function is, so can't ensure at runtime that whatever signal handler you provided is compatible with the signature of the signal. And if they don't match you'll get memory safety issues or worse.

**Comment by PeterOGB** [comment]
Well then at least can https://gtk-rs.org/docs/gtk/struct.Builder.html be updated to remove the text  that says these functions are available.  "The function BuilderExt::connect_signals and variants thereof can be used to connect handlers to the named signals in the description."  I've wasted time looking for these non-existent functions !

**Comment by sdroege** [comment]
@GuillaumeGomez is that possible?

As that documentation comes directly from the C documentation that's a bit tricky probably.

**Comment by GuillaumeGomez** [comment]
It can but it's the C documentation's text. So we'll have to remove it everytime...

**Comment by EPashkin** [comment]
Can we add this text to docs.md? Then IMHO this text from vendor.md will be not used.

**Comment by PeterOGB** [comment]
Consider that for a new rust programmer (like me) finding that the documentation doesn't match the reality (especially when it related to a library that I'm familiar with) is a big problem.  When the  documentation says it works and it doesn't I assume the problem is my code (not the wrong documentation) .

**Comment by GuillaumeGomez** [comment]
I understand your issue, however, we already have a huge load of issues on the documentation. And I'm not really a big fan of the idea of adding a handy fix like that. Nothing prevent you from using the C call directly.

**Comment by sdroege** [comment]
> Nothing prevent you from using the C call directly.

That's not really helpful :) You can't really do that safely, and in theory we could also implement and unsafe function for doing this.

I think we will have to find a generic solution for the docs problem. This is happening more often that the C documentation is plain misleading and we should clarify that a bit on our side.

**Comment by PeterOGB** [comment]
Sorry but I don't know enough about rust yet for that to be a solution !  I though by using Gtk (something I'm familiar with) it would be a good way to learn rust, but it seems that the interface is too incomplete to be a helpful aid to learning rust.

**Comment by sdroege** [comment]
>  it seems that the interface is too incomplete

There are two options here for this specific API
1) We consider it unsafe by design and provide an unsafe API that does not check the signature of signal handlers (that's what you get in all other languages that don't have an interpreter or virtual machine),
2) We provide a safe API for this, but it would work based on `glib::Value` for the arguments and return value. That's ugly to work with as you manually need to unpack everything, but it would be safe,
3) Or we provide both and let the user chose their poison

@PeterOGB what would seem nicer for what you want to do?

**Comment by PeterOGB** [comment]
Sorry, but I don't yet know enough about rust to understand the consequences of either approach.

**Comment by NoraCodes** [comment]
I would really like to have this implemented, even if it only provides `glib::Value` access; most of the time I'm using this API in Python, it's just to connect a few dozen buttons at the same time and I don't even _need_ access to the buttons from the callbacks.

**Comment by sdroege** [comment]
@NoraCodes How would you like to provide the signal closures though? Options I can think of right now would be

1. via a slice of `(&str, Box<dyn Fn(&[glib::Value]) -> Option<glib::Value>>)`
2. passing a selector functions of type `FnMut(&str -> Box<dyn Fn(&[glib::Value]) -> Option<glib::Value>>)` for explicitly selecting each signal handler
3. an actual trait instead of the `FnMut()` above that has such a function
4. One of the above but requiring a plain `fn` instead of a `Fn` closure

> I don't even _need_ access to the buttons from the callbacks.

For many other signals you need the other arguments to do anything meaningful though :) Not necessarily the object itself, but the further arguments that come with the signal.

**Comment by NoraCodes** [comment]
> For many other signals you need the other arguments to do anything meaningful though :) Not necessarily the object itself, but the further arguments that come with the signal.

Fair enough, yeah. Maybe this is solvable using a procmacro? The essential mismatch here is that we want to connect a compile-time construct - a function or closure type signature - with a runtime construct - a Builder. Could we allow generating a Builder with its XML loaded at compile time and then write a macro that does the type-checking based on that XML?

**Comment by sdroege** [comment]
Such a proc macro would be the next step on top of a safe, generic API around `glib::Value` as outlined above. Let's first get that done and then someone can look into creating a proc macro around it :)

Question still is, which of those 4 options would be nicest to use. I'm currently in favour of 2.

**Comment by NoraCodes** [comment]
Personally I am also in favor of option 2.
