### ISSUE TITLE
The executable file must reside in the same dir with gtk dlls

### ISSUE THREAD

**Issue by zoumi** [gtk-rs/gtk#732]
Is there a way to distribute my app and gtk runtime seperately？
Now I have to put these files together.And put gtk dll's dir to PATH didn't work.

**Comment by GuillaumeGomez** [comment]
On windows, I'm not sure. It's pretty common to distribute your binary with the DLLs alongside.

**Comment by sdroege** [comment]
How does it not work to simply put the GTK DLLs into the PATH, what happens if you try to do that?

Having them in the PATH should be enough, but you generally also need to ensure that the GTK DLLs and the other files coming with GTK stay in the same directory structure. E.g. that the DLL is in the bin directory, and next to the bin directory there is the share directory with various other files.

**Comment by sdroege** [comment]
This is a general GTK problem and not related to the bindings, so best discussed at https://discourse.gnome.org
