### ISSUE TITLE
GtkListStoreExt name inconsistent?

### ISSUE THREAD

**Issue by osa1** [gtk-rs/gtk#764]
Normally for a GTK type `Foo` we get a `Foo` struct + `FooExt` trait, but for `ListStore` we get `ListStore` trait + `GtkListStore` trait, so the trait name is inconsistent with other traits. Should we rename it?

**Comment by EPashkin** [comment]
@osa1 Trait was renamed to remove conflict https://github.com/gtk-rs/gtk/blob/master/Gir.toml#L1025 with trait for gio::ListStore

**Comment by sdroege** [comment]
Yes, let's close this one then :) There are more traits like this.

It's mostly a workaround for a bug in how rustc is resolving traits.

**Comment by osa1** [comment]
But `gtk::ListStore` also conflicts with `gio::ListStore`, and we don't add a prefix to it. Why do it for `GtkListStoreExt`?

**Comment by sdroege** [comment]
It's a `struct` and not a `trait`. The problem is only with resolving of `trait`s that have the same name but are in different modules, and the names of the traits don't really matter much for gtk-rs as you almost never will address them directly as a user (but instead would e.g. import `gtk::prelude::*`).
