### ISSUE TITLE
BoxBuilder lacks orientation method

### ISSUE THREAD

**Issue by mmstick** [gtk-rs/gtk#833]
Widget construction defaults to a horizontal layout, so vertical layouts aren't possible unless set outside of the builder.

**Comment by sdroege** [comment]
That's because the orientation is no property. It could be added as a manual function to the builder though. But not sure how to best do it: to create a box you must give an orientation, so ideally it should be part of the constructor of the builder itself. Which is currently not supported. And you'd need to be able to hook into the `build()` function, call some more code there, and most important be able to store the value of the property inside the builder.

This needs some more work on the `gir` side to allow customization of the generated builders. CC @EPashkin @antoyo

**Comment by antoyo** [comment]
Actually, `orientation` is a property: it's [here](http://gtk-rs.org/docs/gtk/trait.OrientableExt.html#tymethod.set_orientation).
I'm not sure why `gir` didn't generate it though.

**Comment by antoyo** [comment]
[This seems already fixed.](https://github.com/gtk-rs/gtk/blob/master/src/auto/box_.rs#L456)

**Comment by sdroege** [comment]
@GuillaumeGomez can be closed
