### ISSUE TITLE
List store must accept other types other than gtk::Type

### ISSUE THREAD

**Issue by ranfdev** [gtk-rs/gtk#851]
Currently a list store only accepts columns with type gtk::Type, so it's impossible to properly use a gtk::IconView, which [requires a TreeModel with a column of type ```GDK_TYPE_PIXBUF```](https://developer.gnome.org/gtk3/stable/GtkIconView.html#gtk-icon-view-set-pixbuf-column)

**Comment by sdroege** [comment]
On 13 July 2019 18:03:42 EEST, ranfdev <notifications@github.com> wrote:
>Currently a list store only accepts columns with type gtk::Type, so
>it's impossible to bind a TreeModel to a gtk::IconView, which requires
>a column to be of type ```GDK_TYPE_PIXBUF```, as noted
>[here](https://developer.gnome.org/gtk3/stable/GtkIconView.html#gtk-icon-view-set-pixbuf-column)

`gdk_pixbuf::Pixbuf::static_type()` gives you the type (`glib::Type` / `gtk::Type`) of the pixbuf. That's the same as that C macro does.


-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sdroege** [comment]
Does this answer your question or is there still something missing?

**Comment by ranfdev** [comment]
> Does this answer your question
Absolutely yes, thank you!

**Comment by merehap** [comment]
I just ran into this issue too, spending hours trying to figure out what the problem was.

Could some documentation be added to ListStore::new(..) about using .static_type() for Pixbufs and similar types that aren't explicitly listed in glib::types::Type? I'm confident that this would save many dev days of effort collectively, especially for people like me who have never worked with GTK prior to programming in Rust.

Thanks!

**Comment by sdroege** [comment]
@GuillaumeGomez How can we do this?

**Comment by GuillaumeGomez** [comment]
We could add a `doc` key in gir maybe?
