### ISSUE TITLE
Application subclasss needs to handle parent delete_event

### ISSUE THREAD

**Issue by alatiera** [gtk-rs/gtk#916]
> Unrelated. The problem is that `delete_event` is `NULL` here and we currently don't handle that in the subclass bindings. We would have to check for which virtual methods it is valid to have `NULL` there and then what the default behaviour should be (another thing for which we don't have g-i annotations...). That requires diving into the C code. I've done that for the things in gio and gstreamer, but nowhere else.

> In this specific case, instead of panicking at that line it should return `false` here if it's `NULL`.

_Originally posted by @sdroege in https://github.com/gtk-rs/examples/pull/256#issuecomment-554977469_

**Comment by sdroege** [comment]
The title is wrong. It's not about handling it instead of setting to `NULL`, but we need to handle the parent one being `NULL` by implementing default behaviour.

In specific, the `expect()` here should be replaced by an `unwrap_or(false)`:
https://github.com/gtk-rs/gtk/blob/e55bd4d30afcabd70fb246163c0d3d18fa36d129/src/subclass/widget.rs#L453

**Comment by sdroege** [comment]
Also CC @BrainBlasted
